### ISSUE TITLE
kubectl.command from the readme does not work as expected

### ISSUE THREAD

**Issue by c-knowles** [Goyoo/node-k8s-client#11]
`kubectl.command` from the readme implies that `K8s.kubectl(...).command` should work. However, the method does not seem to be not define there. `kube.node.command` works although the command is type agnostic so maybe this should be exposed another way.

**Comment by junjun16818** [comment]
Sorry. This is my fault
fixed

**Comment by c-knowles** [comment]
I think it's mostly fixed now although some of this area could do with a tidy so it doesn't go via `pod`.

I'm not sure if it's compatible but today I was trying to use `kubectl.command` with `async.apply` from the popular [async](https://www.npmjs.com/package/async) package. I wanted to run a set of commands together using the existing control flow. I received the below. I ended up doing it another way, but it does indicate some of these would perhaps be separate out. I may look at that if I get a chance.

```
TypeError: Cannot read property 'pod' of null
    at command (/app/node_modules/k8s/index.js:492:25)
    at /app/node_modules/async/dist/async.js:1263:23
    at /app/node_modules/async/dist/async.js:338:31
    at /app/node_modules/async/dist/async.js:3671:13
    at eachOfArrayLike (/app/node_modules/async/dist/async.js:1002:13)
    at eachOf (/app/node_modules/async/dist/async.js:1052:9)
    at _parallel (/app/node_modules/async/dist/async.js:3670:9)
    at Object.parallelLimit [as parallel] (/app/node_modules/async/dist/async.js:3750:7)
```
