### ISSUE TITLE
Support for Typescript (2?)

### ISSUE THREAD

**Issue by kundralaci** [Goyoo/node-k8s-client#16]
Recently we have moved to Typescript 2, and it seems stable and all our projects build, work, etc...

**Problem**

However building k8s with Typescript 2.0.0, I get the following errors:

```
app.ts(5,10): error TS2305: Module '"/home/laci/ktest/node_modules/k8s/index"' has no exported member 'K8s'.
node_modules/k8s/lib/request.ts(2,7): error TS2529: Duplicate identifier 'Promise'. Compiler reserves name 'Promise' in top level scope of a module containing async functions.
node_modules/k8s/lib/request.ts(223,1): error TS4082: Default export of the module has or is using private name 'Request'.
```

From these errors, even earlier Typescript compilers were crying for `no exported member 'K8s'`.

**Environment**

I'm using node@6.3.1 and npm 3+.
I prepared a very simple project with only a single `app.ts`, that would call `K8s.api(...)`:

```
import { K8s } from 'k8s';

let kubeapi = K8s.api({
	endpoint: '...',
	version: '/api/v1',
	auth: {
		clientCert: '...',
		clientKey: '...',
		caCert: '...'
	},
	strictSSL: false
});
```

My tsconfig.json:

```
"compilerOptions": {
    "target": "ES6",
    "module": "commonjs",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "declaration": true
}
```

**Proposals / Questions:**

Looking at the 3 errors:

- The first: can be my mistake(?), I'm unsure.
- The second: Why do we need an external promise library?
- The third: Maybe a little restructure, refactor could solve this. (?)

**Comment by kundralaci** [comment]
Wow, nice to see that my PR has been merged so quickly! :)

Issue solved!

You may also update the readme, so that `tsd install` now can be / should be removed.

**Comment by junjun16818** [comment]
Thanks for you code. you code very cool
now have one problem . if use ` export default K8s` can't  exact output to js file.  
```
var K8s = require('k8s')
console.log(K8s)
// { default: { api: [Function], kubectl: [Function] } } 
```
if use `export = K8s` 
```
import { K8s } from 'k8s';
//Module '"/Users/junjun16818/Project/junjun16818/node-k8s-client/index"' has no default export.
import K8s
```
do you have a good idea ?

**Comment by kundralaci** [comment]
Right, I had some mistakes!

Just a sec, and I create a new PR!

**Comment by kundralaci** [comment]
Just made the new PR.
Now you can write the code as you mentioned:
```
var K8s = require('k8s');
console.log(K8s);
console.log(K8s.api);
```
And have a result like this:
```
$ node test.js
{ api: [Function], kubectl: [Function] }
[Function]
```

**Comment by junjun16818** [comment]
It works perfectly

**Comment by kundralaci** [comment]
Thanks!
I made some tests and it goes all good!
