### ISSUE TITLE
[Feature] Add possibility to fetch pod logs using the REST API

### ISSUE THREAD

**Issue by laddi** [Goyoo/node-k8s-client#21]
The problem is obvious, calling `K8s.api({ ... }).get('namespaces/xxx/pods/yyy/logs')` will always throw an error since the result is plaintext and not application/json.  Not sure how to handle this properly, though...

**Comment by sputnick** [comment]
In other words the problem is the "resolve(JSON.parse(data));" in the get method. Using post doesn't help.

**Comment by junjun16818** [comment]
Sorry  This is my fault

Please upgrate module to 0.4.9
Use `log` function
```
K8s.api({ ... }).log('namespaces/xxx/pods/yyy/logs')
```

**Comment by sputnick** [comment]
Awesome! Thanks for the quick help.

**Comment by laddi** [comment]
Thanks a bunch, especially for a speedy reply and fix! 😄
