### ISSUE TITLE
HTTP content-type headers for PATCH request

### ISSUE THREAD

**Issue by pichouk** [Goyoo/node-k8s-client#26]
Few days ago I submitted PR #24. this PR is close because I saw that the fix was commit (https://github.com/Goyoo/node-k8s-client/commit/cbd2163a74a34e734cc2c0c63e3ba22c1d5f2adbà) to set `Content-Type` HTTP header to `application/strategic-merge-patch+json` for PATCH request.
But another commit (https://github.com/Goyoo/node-k8s-client/commit/41555e8ef8e2129495db77b9d1473a00d82fa9d4) set `Content-Type` header to `application/json-patch+json`.

The PATCH request works for me only if header is `Content-Type` is `application/strategic-merge-patch+json`. When I use `kubectl patch --v=8 [...]` (to see what request are made to Kubernetes API) I see that `Content-Type` is `application/strategic-merge-patch+json` so it seems to be the right value.

**Comment by junjun16818** [comment]
I added a options to the patch function
kubeapi.patch('url', {}, {headers: { 'Content-Type': 'application/strategic-merge-patch+json' }})

**Comment by pichouk** [comment]
Works great for me, thanks !
