### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by Btlyons1** [Goyoo/node-k8s-client#3]
Is there a specific way to authenticate with a token or using another method?

**Comment by junjun16818** [comment]
Added ability to configure kubectl via kubeconfig rather than point a…
…t an endpoint.

 - Kubeconfig is preferred if it exists
 - Currently endpoint and kubeconfig are mutually exclusive at this time
 - Backwards compatible

```
var k = require('k8s');

// Configure using endpoint
var kube = k.kubectl({
	endpoint: 'http://my-cluster'
	,binary: '/bin/kubectl'
	,version: 'v1'
});

// Configure using kubeconfig
var kube = k.kubectl({
	binary: '/bin/kubectl'
	,kubeconfig: '/etc/cluster1.yaml'
	,version: 'v1'
});
```

**Comment by andreassolberg** [comment]
I also missed support for authentication on the API, so I added a pull request:

https://github.com/Goyoo/node-k8s-client/pull/4
