### ISSUE TITLE
Incorrect implementation for finding cluster from kubeconfig

### ISSUE THREAD

**Issue by philidem** [Goyoo/node-k8s-client#31]
You're currently using:

```javascript
return kubeconfig.clusters.find(x => x.name === context.name)
```

Should be:

```javascript
return kubeconfig.clusters.find(x => x.name === context.context.cluster)
```

To clarify, the current implementation assumes that the context name will always match the cluster name. The correct method is to read the `context.cluster` property of the `context` when searching for `cluster`.

**Comment by philidem** [comment]
I'll have a pull request shortly. I just started trying this library and this was the first problem I encountered. I like the low-level simplicity of this so far.

**Comment by junjun16818** [comment]
Thank you for helping to solve this problem
