### ISSUE TITLE
Add to list of user contributed client libraries

### ISSUE THREAD

**Issue by philidem** [Goyoo/node-k8s-client#32]
You should consider adding this library to https://github.com/kubernetes/community/blob/master/contributors/devel/client-libraries.md

I'm just starting to evaluate this library but I like it so far for a couple of reasons:

- Support for promises (`async`/`await`)
- Low-level URL building (makes it a little more future-proof)

You'll probably want to improve the quality of the `README.md` a little.

**Comment by shenshouer** [comment]
It`s good idea to adding this library to client-libraries. We have created the PR https://github.com/kubernetes/community/pull/576

**Comment by shenshouer** [comment]
I think this issue can close. If any question, please reopen it.
https://github.com/kubernetes/kubernetes.github.io/pull/4524
